import type { Metadata } from "next";
import Image from "next/image";

import { Inter } from "next/font/google";
import "./globals.css";

import AppWrapper from "@/components/AppWrapper";

import metamaskLogo from "@/public/metamask.svg";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <AppWrapper>
          <nav className="flex flex-row items-center align-center justify-center w-full h-[70px] backdrop-blur-md bg-[#403D43] py-2 px-16 border-2 border-gray-600">
            <button className="btn">
              <Image
                src={metamaskLogo}
                alt="Metamask logo"
                width={20}
                height={20}
              />
              Install Push Protocol Snap to receive live notification.
              <span className="underline">Read more</span>
            </button>
          </nav>
          <main className="bg-dark">
            <Navbar />

            <div className="flex min-h-screen flex-col items-center gap-4 w-[90%] mx-auto justify-between">
              {children}
            </div>
          </main>
        </AppWrapper>
      </body>
    </html>
  );
}
