import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

import { Web3ModalProvider } from "@/context/Web3Modal";
import ConnectButton from "@/components/ConnectButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3ModalProvider>
          <main className="flex min-h-screen flex-col items-center gap-4 p-8 bg-dark">
            <nav className="flex flex-row items-center align-center justify-between w-[90%] h-[70px] rounded-full backdrop-blur-md bg-white/10 py-2 px-16 border-2 border-gray-600">
              <Link
                href="/"
                className="text-xl font-bold underline underline-p-4 hover:text-slate-300 transition ease-in-out"
              >
                BRND.sh
              </Link>
              <ConnectButton />
            </nav>
            {children}
          </main>
        </Web3ModalProvider>
      </body>
    </html>
  );
}
